spring:
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8090

management:
  otlp:
    tracing:
      endpoint: http://localhost:4317
  tracing:
    enabled: true
    sampling.probability: 1.0

  #zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  service:
    name: otel-gateway-api
